#index:
#    path: /
#    controller: App\Controller\DefaultController::index

get_random_questions:
  path: '/api/randomm'
  methods: ['GET']
  defaults:
    _controller: '\App\Controller\GetRandomQuestionController::getRandom'
    _api_resource_class: 'App\Entity\Question'
    _api_collection_operation_name: 'get_random_questions'
